name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ⚙️
        run: npm ci

      - name: Lint ⛓️
        run: npm run lint

      - name: Test 🧪
        run: npm run test

      - name: Build 🛠️
        run: npm run build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          APPID: ${{ secrets.APPID }}
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FINANCE_A316B }}
          channelId: live
          projectId: ${{ secrets.PROJECT_ID }}
